=== Ilya1vanov/Archive/src/test/resources/xsd/employee.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.ilya.ivanov.com/archive/employee"
           elementFormDefault="qualified"
           xmlns:e="https://www.ilya.ivanov.com/archive/employee">

    <!--type definitions-->
    <xs:simpleType name="nameType">
        <xs:restriction base="xs:normalizedString">
            <xs:pattern value="[A-Z][a-z]+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="sexType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="male"/>
            <xs:enumeration value="female"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="employeeMetaType">
        <xs:sequence>
            <xs:element name="firstName" type="e:nameType"/>
            <xs:element name="middleName" type="e:nameType"/>
            <xs:element name="lastName" type="e:nameType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="employee">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employeeMeta" type="e:employeeMetaType"/>
                <xs:element name="sex" type="e:sexType"/>
                <xs:element name="age" type="xs:unsignedInt"/>
                <xs:element name="workplace" type="xs:string"/>
                <xs:element name="experience" type="xs:unsignedInt"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:unsignedInt" use="optional"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Ilya1vanov/Archive/src/test/resources/testEmp.xml
<?xml version="1.0" encoding="UTF-8"?>

<employee   xmlns="https://www.ilya.ivanov.com/archive/employee"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="https://www.ilya.ivanov.com/archive/employee xsd/employee.xsd"
            id="1">
    <employeeMeta>
        <firstName>Ilya</firstName>
        <middleName>Petrovich</middleName>
        <lastName>Ivanov</lastName>
    </employeeMeta>
    <sex>male</sex>
    <age>19</age>
    <workplace>bsuir</workplace>
    <experience>2</experience>
</employee>
